// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POAM.Models;

namespace POAM.Migrations
{
    [DbContext(typeof(POAMDbContext))]
    partial class POAMDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("POAM.Models.Apartment", b =>
                {
                    b.Property<int>("IdApartment")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double?>("CurrentDebt");

                    b.Property<string>("FlatNo")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("IdOwner");

                    b.Property<byte?>("NoTenants");

                    b.Property<double?>("PreviousDebt");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double?>("TotalDebt");

                    b.HasKey("IdApartment");

                    b.HasIndex("IdOwner");

                    b.ToTable("Apartment");
                });

            modelBuilder.Entity("POAM.Models.Contract", b =>
                {
                    b.Property<int>("IdContract")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<double>("Price");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("IdContract");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("POAM.Models.Employee", b =>
                {
                    b.Property<int>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(50);

                    b.Property<string>("Employment")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Pid")
                        .IsRequired()
                        .HasColumnName("PID")
                        .HasMaxLength(50);

                    b.Property<double>("Salary");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("IdEmployee");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("POAM.Models.Owner", b =>
                {
                    b.Property<int>("IdOwner")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool?>("IsAdmin")
                        .HasColumnName("isAdmin");

                    b.Property<string>("PassSalt");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("IdOwner");

                    b.ToTable("Owner");
                });

            modelBuilder.Entity("POAM.Models.Receipt", b =>
                {
                    b.Property<int>("IdReceipt")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("IdApartment");

                    b.HasKey("IdReceipt");

                    b.HasIndex("IdApartment");

                    b.ToTable("Receipt");
                });

            modelBuilder.Entity("POAM.Models.WaterConsumption", b =>
                {
                    b.Property<int>("IdWaterConsumption")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ColdWater");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("IdApartment");

                    b.Property<int?>("WarmWater");

                    b.HasKey("IdWaterConsumption");

                    b.HasIndex("IdApartment");

                    b.ToTable("WaterConsumption");
                });

            modelBuilder.Entity("POAM.Models.Apartment", b =>
                {
                    b.HasOne("POAM.Models.Owner", "IdOwnerNavigation")
                        .WithMany("Apartment")
                        .HasForeignKey("IdOwner")
                        .HasConstraintName("FK_Apartment_Owner")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("POAM.Models.Receipt", b =>
                {
                    b.HasOne("POAM.Models.Apartment", "IdApartmentNavigation")
                        .WithMany("Receipt")
                        .HasForeignKey("IdApartment")
                        .HasConstraintName("FK_Receipt_Apartment")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("POAM.Models.WaterConsumption", b =>
                {
                    b.HasOne("POAM.Models.Apartment", "IdApartmentNavigation")
                        .WithMany("WaterConsumption")
                        .HasForeignKey("IdApartment")
                        .HasConstraintName("FK_WaterConsumption_Apartment")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
